baseurl = "https://ggc.yurimdias.science"
languageCode = "en"

title = "Gold, Glory and Citations"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true
# summarylength = 30
paginate = 10

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    en = "/en/:year/:month/:slug/"
    pt = "/pt/:year/:month/:slug/"

## Site Settings
[params]
    author = "Yuri-M-Dias"
    title = "Gold, Glory and Citations"
    description = "Science, engineering and related stuff."
    authorimage = "/img/hugo.png"
    dateformat = "2 Jan 2006"

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    UtterancesRepo = "Yuri-M-Dias/ggc" # https://utteranc.es/
    UtterancesIssueTerm = "og:title" # pathname, url, title, og:title
    UtterancesTheme = "github-light" # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "Yuri-M-Dias"
    stackoverflow = "3312701"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "EN"
    weight = 200
    identifier = "en"
    url = "/en/"
[[menu.main]]
    name = "PT"
    weight = 200
    identifier = "pt"
    url = "/pt/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
# EN Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/en-about/"
# PT Menu
[[menu.main]]
    name = "Sobre"
    identifier = "sobre"
    weight = 300
    url = "/pt-sobre/"
