baseurl = "/"
languageCode = "en"

title = "Gold, Glory and Citations"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

paginate = 10

## Site Settings
[params]
    author = "Yuri-M-Dias"
    title = "Gold, Glory and Citations"
    description = "Science, engineering and related stuff."
    authorimage = "/img/hugo.png"
    dateformat = "2 Jan 2006"

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    UtterancesRepo = "Yuri-M-Dias/ggc" # https://utteranc.es/
    UtterancesIssueTerm = "pathname" # pathname, url, title, og:title
    UtterancesTheme = "github-light" # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "Yuri-M-Dias"
    stackoverflow = "yuri-m-dias"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
